[platformio]

default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32@6.13.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 16MB
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi

platform_packages =
  framework-arduinoespressif32@3.20017.241212+sha.dcc1105b

lib_deps =
  bblanchon/ArduinoJson@7.4.3
  joaolopesf/RemoteDebug@3.0.5
  tzapu/WiFiManager@2.0.17
  esp32async/ESPAsyncWebServer@3.10.3
  esp32async/AsyncTCP@3.4.10
  https://github.com/lewisxhe/TinyGSM-fork#9c19d515f16215311d4d83c628d10e7e2e4b1cdc

build_flags =
  -I include
  -DBOARD_HAS_PSRAM
  -DWEBSOCKET_DISABLED
  -DTINY_GSM_MODEM_SIM7600

upload_speed = 2000000
;upload_speed = 921600
monitor_speed = 115200

build_type = debug
monitor_filters = esp32_exception_decoder

[env:native]
platform = native
test_framework = unity
test_build_src = no
lib_compat_mode = off
build_flags = -I test/support -I src
lib_deps =
  bblanchon/ArduinoJson@7.4.3
