/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an authenticated admin session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current admin session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get overall device health and connectivity status */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current device configuration
         * @description Returns the stored config JSON by streaming the file as-is from device storage, without reconstructing or fully buffering large documents in memory.
         */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/station": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update station configuration */
        put: operations["updateStationConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/sampling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update sampling configuration */
        put: operations["updateSamplingConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/smoothing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update smoothing configuration */
        put: operations["updateSmoothingConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update storage configuration */
        put: operations["updateStorageConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update network configuration */
        put: operations["updateNetworkConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/sms-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update SMS admin configuration */
        put: operations["updateSmsAdminConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/web-ui": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update web UI configuration */
        put: operations["updateWebUiConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update sensor configuration */
        put: operations["updateSensorsConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/publishers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update publisher configuration */
        put: operations["updatePublishersConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sensors/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the latest raw and smoothed weather measurements */
        get: operations["getLatestSensorReadings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the full recent-log JSON document
         * @description Returns the stored recent-log JSON by streaming it as-is from device storage, without filtering or full in-memory loading.
         */
        get: operations["getRecentLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the full retained weather history document
         * @description Returns the stored history JSON by streaming it as-is from device storage, without filtering or full in-memory loading.
         */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/connectivity/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a connectivity test using wifi or cellular */
        post: operations["testConnectivity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/publishers/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a test publish for one or more configured publishers */
        post: operations["testPublishers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example validation_error */
            error: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            accessToken: string;
            /** @enum {string} */
            tokenType: "Bearer";
            /** Format: date-time */
            expiresAt: string;
        };
        LogoutResponse: {
            loggedOut: boolean;
        };
        DeviceStatusResponse: {
            device: components["schemas"]["DeviceSummary"];
            connectivity: components["schemas"]["ConnectivityStatus"];
            storage: components["schemas"]["StorageStatus"];
            sampling: components["schemas"]["SamplingStatus"];
            adminWindow: components["schemas"]["AdminWindowStatus"];
            sensors: components["schemas"]["SensorStatus"][];
            publishers: components["schemas"]["PublisherStatus"][];
        };
        DeviceSummary: {
            deviceId: string;
            firmwareVersion: string;
            hardwareModel?: string;
            uptimeSeconds: number;
            /** Format: date-time */
            currentTime: string;
            lastBootReason?: string;
        };
        ConnectivityStatus: {
            /** @enum {string} */
            activeTransport: "none" | "wifi" | "cellular";
            wifi: components["schemas"]["WifiStatus"];
            cellular: components["schemas"]["CellularStatus"];
        };
        WifiStatus: {
            enabled: boolean;
            connected: boolean;
            ssid?: string;
            ipAddress?: string;
            rssiDbm?: number;
        };
        CellularStatus: {
            enabled: boolean;
            registered: boolean;
            /** @example SIM7670G */
            modemType: string;
            operatorName?: string;
            signalQuality?: number;
            ipv4?: string;
            ipv6?: string;
            imei?: string;
        };
        StorageStatus: {
            sdCardPresent: boolean;
            freeBytes?: number;
            usedBytes?: number;
            retentionDays: number;
            /** Format: date-time */
            oldestRecordAt?: string;
            /** Format: date-time */
            newestRecordAt?: string;
        };
        SamplingStatus: {
            intervalSeconds: number;
            /** Format: date-time */
            nextSampleAt: string;
            /** Format: date-time */
            lastSampleAt: string;
            sleepEnabled: boolean;
            smoothingEnabled?: boolean;
        };
        AdminWindowStatus: {
            active: boolean;
            /** Format: date-time */
            openedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** @description SMS sender number or web user identifier */
            requestedBy?: string;
        };
        SensorStatus: {
            id: string;
            /** @example sen0658 */
            kind: string;
            enabled: boolean;
            healthy: boolean;
            /** Format: date-time */
            lastReadAt?: string;
            message?: string;
        };
        PublisherStatus: {
            id: string;
            /** @enum {string} */
            type: "wunderground" | "windy" | "webhook" | "mqtt";
            enabled: boolean;
            /** Format: date-time */
            lastPublishAt?: string;
            /** @enum {string} */
            lastResult?: "unknown" | "success" | "failed";
            message?: string;
        };
        DeviceConfigView: {
            schemaVersion: number;
            station: components["schemas"]["StationConfig"];
            sampling: components["schemas"]["SamplingConfig"];
            smoothing: components["schemas"]["SmoothingConfig"];
            storage: components["schemas"]["StorageConfig"];
            network: components["schemas"]["NetworkConfig"];
            smsAdmin: components["schemas"]["SmsAdminConfig"];
            webUi: components["schemas"]["WebUiConfig"];
            sensors: components["schemas"]["SensorConfig"][];
            publishers: components["schemas"]["PublisherConfigView"][];
        };
        StationConfig: {
            stationName: string;
            /** @example Asia/Kolkata */
            timezone: string;
            location: components["schemas"]["GeoLocation"];
            notes?: string;
        };
        GeoLocation: {
            latitude: number;
            longitude: number;
            elevationMeters?: number;
        };
        SamplingConfig: {
            /** @default 30 */
            intervalSeconds: number;
            /** @default 10 */
            adminWindowMinutes: number;
            /** @default true */
            deepSleepEnabled: boolean;
            wakeDurationSeconds?: number;
            /** @default 30 */
            historyAggregationMinutes: number;
        };
        SmoothingConfig: {
            enabled: boolean;
            fields: components["schemas"]["SmoothingFieldConfig"][];
        };
        SmoothingFieldConfig: {
            /** @enum {string} */
            metric: "windSpeed" | "windGust" | "windDirection" | "temperature" | "humidity" | "pressure" | "rainfall" | "illuminance" | "pm2_5" | "pm10" | "noise";
            /** @enum {string} */
            method: "none" | "moving_average" | "ema";
            windowSamples?: number;
            alpha?: number;
        };
        StorageConfig: {
            /** @default 14 */
            retentionDays: number;
            /** @enum {string} */
            logFormat: "jsonl";
            /** @enum {string} */
            configSource?: "sd_with_flash_fallback";
        };
        NetworkConfig: {
            /** @enum {string} */
            preferredTransport: "wifi" | "cellular" | "auto";
            wifi: components["schemas"]["WifiConfig"];
            cellular: components["schemas"]["CellularConfig"];
        };
        WifiConfig: {
            enabled: boolean;
            ssid: string;
            passwordConfigured?: boolean;
            allowedOrigins?: string[];
        };
        CellularConfig: {
            enabled: boolean;
            /** @enum {string} */
            modemType: "SIM7670G";
            apn?: string;
            pinConfigured?: boolean;
            smsEnabled?: boolean;
        };
        SmsAdminConfig: {
            enabled: boolean;
            whitelist: components["schemas"]["PhoneWhitelistEntry"][];
            commands: ("OPEN_SESAME" | "STATUS" | "HELP" | "CONFIG_GET" | "CONFIG_SET" | "NET" | "PUBLISH_NOW")[];
        };
        PhoneWhitelistEntry: {
            label: string;
            /**
             * @description E.164 formatted number
             * @example +919876543210
             */
            phoneNumber: string;
        };
        WebUiConfig: {
            /** @default 15 */
            tokenTtlMinutes: number;
            allowedOrigins: string[];
        };
        SensorConfig: {
            id: string;
            /** @enum {string} */
            type: "sen0658" | "bme280" | "bmp390" | "lps22hb";
            enabled: boolean;
            /** @enum {string} */
            transport?: "rs485_modbus" | "i2c" | "spi";
            settings?: {
                [key: string]: unknown;
            };
        };
        PublisherConfigView: components["schemas"]["WundergroundPublisherView"] | components["schemas"]["WindyPublisherView"] | components["schemas"]["WebhookPublisherView"] | components["schemas"]["MqttPublisherView"];
        PublisherConfigInput: components["schemas"]["WundergroundPublisherInput"] | components["schemas"]["WindyPublisherInput"] | components["schemas"]["WebhookPublisherInput"] | components["schemas"]["MqttPublisherInput"];
        PublisherBaseView: {
            id: string;
            type: string;
            enabled: boolean;
            publishIntervalSeconds: number;
            includeHistoryWindowMinutes?: number;
        };
        PublisherBaseInput: {
            id: string;
            type: string;
            enabled: boolean;
            publishIntervalSeconds: number;
            includeHistoryWindowMinutes?: number;
        };
        WundergroundPublisherView: components["schemas"]["PublisherBaseView"] & {
            /** @constant */
            type: "wunderground";
            stationId: string;
            apiKeyConfigured: boolean;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "WundergroundPublisherView";
        };
        WundergroundPublisherInput: components["schemas"]["PublisherBaseInput"] & {
            /** @constant */
            type: "wunderground";
            stationId: string;
            apiKey?: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "WundergroundPublisherInput";
        };
        WindyPublisherView: components["schemas"]["PublisherBaseView"] & {
            /** @constant */
            type: "windy";
            stationId: string;
            apiKeyConfigured: boolean;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "WindyPublisherView";
        };
        WindyPublisherInput: components["schemas"]["PublisherBaseInput"] & {
            /** @constant */
            type: "windy";
            stationId: string;
            apiKey?: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "WindyPublisherInput";
        };
        WebhookPublisherView: components["schemas"]["PublisherBaseView"] & {
            /** @constant */
            type: "webhook";
            /** Format: uri */
            endpoint: string;
            authHeaderConfigured?: boolean;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "WebhookPublisherView";
        };
        WebhookPublisherInput: components["schemas"]["PublisherBaseInput"] & {
            /** @constant */
            type: "webhook";
            /** Format: uri */
            endpoint: string;
            authHeader?: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "WebhookPublisherInput";
        };
        MqttPublisherView: components["schemas"]["PublisherBaseView"] & {
            /** @constant */
            type: "mqtt";
            /** Format: uri */
            brokerUrl: string;
            topic: string;
            username: string;
            passwordConfigured: boolean;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MqttPublisherView";
        };
        MqttPublisherInput: components["schemas"]["PublisherBaseInput"] & {
            /** @constant */
            type: "mqtt";
            /** Format: uri */
            brokerUrl: string;
            topic: string;
            username: string;
            password: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MqttPublisherInput";
        };
        LatestSensorReadingsResponse: {
            latest: components["schemas"]["WeatherSample"];
            smoothed: components["schemas"]["SmoothedWeatherSample"];
        };
        WeatherLogResponse: {
            samples: components["schemas"]["WeatherSample"][];
        };
        WeatherHistoryResponse: {
            samples: components["schemas"]["WeatherSample"][];
        };
        WeatherSample: {
            /** Format: date-time */
            recordedAt: string;
            temperatureC?: number;
            humidityPct?: number;
            pressureHpa?: number;
            windSpeedMps?: number;
            windGustMps?: number;
            windDirectionDeg?: number;
            rainfallMm?: number;
            illuminanceLux?: number;
            pm2_5UgM3?: number;
            pm10UgM3?: number;
            noiseDb?: number;
        };
        SmoothedWeatherSample: components["schemas"]["WeatherSample"] & {
            smoothingApplied?: boolean;
        };
        ConnectivityTestRequest: {
            /** @enum {string} */
            transport?: "auto" | "wifi" | "cellular";
            /** Format: uri */
            targetUrl?: string;
        };
        ConnectivityTestResponse: {
            success: boolean;
            /** Format: date-time */
            checkedAt: string;
            /** @enum {string} */
            transportUsed?: "wifi" | "cellular";
            latencyMs?: number;
            message?: string;
        };
        PublisherTestRequest: {
            publisherIds?: string[];
        };
        PublisherTestResponse: {
            results: {
                publisherId: string;
                success: boolean;
                message?: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current device status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceStatusResponse"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceConfigView"];
                };
            };
        };
    };
    updateStationConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StationConfig"];
            };
        };
        responses: {
            /** @description Updated station configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationConfig"];
                };
            };
            /** @description Configuration validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateSamplingConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SamplingConfig"];
            };
        };
        responses: {
            /** @description Updated sampling configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SamplingConfig"];
                };
            };
            /** @description Configuration validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateSmoothingConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmoothingConfig"];
            };
        };
        responses: {
            /** @description Updated smoothing configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmoothingConfig"];
                };
            };
            /** @description Configuration validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateStorageConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorageConfig"];
            };
        };
        responses: {
            /** @description Updated storage configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageConfig"];
                };
            };
            /** @description Configuration validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateNetworkConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NetworkConfig"];
            };
        };
        responses: {
            /** @description Updated network configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkConfig"];
                };
            };
            /** @description Configuration validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateSmsAdminConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmsAdminConfig"];
            };
        };
        responses: {
            /** @description Updated SMS admin configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmsAdminConfig"];
                };
            };
            /** @description Configuration validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateWebUiConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebUiConfig"];
            };
        };
        responses: {
            /** @description Updated web UI configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebUiConfig"];
                };
            };
            /** @description Configuration validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateSensorsConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensorConfig"][];
            };
        };
        responses: {
            /** @description Updated sensor configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorConfig"][];
                };
            };
            /** @description Configuration validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updatePublishersConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublisherConfigInput"][];
            };
        };
        responses: {
            /** @description Updated publisher configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublisherConfigView"][];
                };
            };
            /** @description Configuration validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLatestSensorReadings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest sensor readings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestSensorReadingsResponse"];
                };
            };
        };
    };
    getRecentLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full recent-log JSON as currently stored by the device */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherLogResponse"];
                };
            };
        };
    };
    getHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full history JSON as currently stored by the device */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherHistoryResponse"];
                };
            };
        };
    };
    testConnectivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConnectivityTestRequest"];
            };
        };
        responses: {
            /** @description Connectivity test completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectivityTestResponse"];
                };
            };
        };
    };
    testPublishers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PublisherTestRequest"];
            };
        };
        responses: {
            /** @description Publisher test completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublisherTestResponse"];
                };
            };
        };
    };
}
